using Xunit;
using Valid.Mcp;
using Valid.Testing.Models;
using System.Text.Json;

namespace Valid.Testing
{
    public class McpToolsTests
    {
        [Fact]
        public void Test_AutoGenerated_MCP_Tools_Lifecycle()
        {
            // 1. Create instance via MCP tool
            var createJson = BasicTestModelMcpTools.valid_create_BasicTestModel();
            Assert.NotNull(createJson);
            
            var createResult = JsonSerializer.Deserialize<CreateResult>(createJson);
            Assert.NotNull(createResult);
            Assert.False(string.IsNullOrEmpty(createResult.instanceId));
            
            var id = createResult.instanceId;

            // 2. Fetch state via MCP tool
            var stateJson = BasicTestModelMcpTools.valid_get_BasicTestModel_state(id);
            Assert.NotNull(stateJson);
            
            var stateResult = JsonSerializer.Deserialize<StateResult>(stateJson);
            Assert.NotNull(stateResult);
            Assert.Equal("BasicTestModel", stateResult.TypeName);
            Assert.Equal(0, stateResult.Values.Age);
            Assert.Equal(string.Empty, stateResult.Values.Name);
            Assert.False(stateResult.IsDirty);
            Assert.True(stateResult.IsValid);

            // 3. Mutate age via MCP tool
            var mutateAgeJson = BasicTestModelMcpTools.valid_set_BasicTestModel_Age(id, 25);
            Assert.NotNull(mutateAgeJson);
            
            var mutateAgeResult = JsonSerializer.Deserialize<MutateResult<int>>(mutateAgeJson);
            Assert.NotNull(mutateAgeResult);
            Assert.True(mutateAgeResult.success);
            Assert.Equal(25, mutateAgeResult.value);
            Assert.True(mutateAgeResult.isDirty);

            // 4. Mutate name via MCP tool
            var mutateNameJson = BasicTestModelMcpTools.valid_set_BasicTestModel_Name(id, "Test Name");
            Assert.NotNull(mutateNameJson);
            
            var mutateNameResult = JsonSerializer.Deserialize<MutateResult<string>>(mutateNameJson);
            Assert.NotNull(mutateNameResult);
            Assert.True(mutateNameResult.success);
            Assert.Equal("Test Name", mutateNameResult.value);
            Assert.True(mutateNameResult.isDirty);

            // 5. Fetch updated state and assert
            var updatedStateJson = BasicTestModelMcpTools.valid_get_BasicTestModel_state(id);
            var updatedStateResult = JsonSerializer.Deserialize<StateResult>(updatedStateJson);
            Assert.NotNull(updatedStateResult);
            Assert.Equal(25, updatedStateResult.Values.Age);
            Assert.Equal("Test Name", updatedStateResult.Values.Name);
            Assert.True(updatedStateResult.IsDirty);

            // 6. Clean up registry
            ValidObjectRegistry.Unregister(id);
            var missingStateJson = BasicTestModelMcpTools.valid_get_BasicTestModel_state(id);
            Assert.Contains("error", missingStateJson);
        }

        private class CreateResult
        {
            public string instanceId { get; set; } = "";
        }

        private class StateResult
        {
            public string InstanceId { get; set; } = "";
            public string TypeName { get; set; } = "";
            public bool IsDirty { get; set; }
            public bool IsValid { get; set; }
            public ValuesResult Values { get; set; } = new();
        }

        private class ValuesResult
        {
            public int Age { get; set; }
            public string Name { get; set; } = "";
        }

        private class MutateResult<T>
        {
            public bool success { get; set; }
            public T? value { get; set; }
            public bool isDirty { get; set; }
            public bool hasError { get; set; }
        }
    }
}
